const getters = {
  sidebar: state => state.app.sidebar,
  language: state => state.app.language,
  topModel: state => state.app.topModel,
  size: state => state.app.size,
  device: state => state.app.device,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  groupNames: state => state.user.groupNames,
  id: state => state.user.id,
  username: state => state.user.username,
  code: state => state.user.code,
  introduction: state => state.user.introduction,
  status: state => state.user.status,
  roles: state => state.user.roles,
  setting: state => state.user.setting,
  permission_routes: state => state.permission.routes,
  addRouters: state => state.permission.addRouters,
  errorLogs: state => state.errorLog.logs,
  permissionMenus: state => state.user.permissionMenus,
  menus: state => state.user.menus,
  elements: state => state.user.elements
}
export default getters
